import type { Drawing, Issue } from './App';

// Helper function to get demo issues for a project
export function getDemoIssues(projectId: string, drawingId: string): Issue[] {
  const issues: Record<string, Record<string, Issue[]>> = {
    '1': { // Downtown Transit Hub
      'drawing-1': [
        {
          id: 'issue-1-1',
          drawingId: 'drawing-1',
          pageNumber: 1,
          x: 0.25,
          y: 0.30,
          type: 'Missing Dimension/Callout',
          severity: 'High',
          description: 'Critical dimension missing for underground parking ramp slope at Station 45+20. Required per Section 4.2.3 of specifications.',
          status: 'Open',
          createdBy: 'AI Assistant',
          aiGenerated: true,
          timestamp: new Date(2024, 0, 16, 10, 30),
        },
        {
          id: 'issue-1-2',
          drawingId: 'drawing-1',
          pageNumber: 1,
          x: 0.55,
          y: 0.45,
          type: 'Code Compliance Concern',
          severity: 'Medium',
          description: 'Potential ADA compliance issue: Elevator lobby clear width appears insufficient. Minimum 60" required per ADAAG 4.3.3.',
          status: 'In Review',
          createdBy: 'AI Assistant',
          aiGenerated: true,
          timestamp: new Date(2024, 0, 16, 10, 32),
        },
        {
          id: 'issue-1-3',
          drawingId: 'drawing-1',
          pageNumber: 1,
          x: 0.75,
          y: 0.25,
          type: 'Grading/Elevation Issue',
          severity: 'High',
          description: 'Inconsistent elevation data: Finish floor elevation 245.3\' conflicts with site grading showing ~246.1\'. Verify against survey.',
          status: 'Open',
          createdBy: 'AI Assistant',
          aiGenerated: true,
          timestamp: new Date(2024, 0, 16, 10, 35),
        },
        {
          id: 'issue-1-4',
          drawingId: 'drawing-1',
          pageNumber: 1,
          x: 0.40,
          y: 0.70,
          type: 'Specification Inconsistency',
          severity: 'Low',
          description: 'Detail reference calls out Detail 5/C3.1, but detail sheet shows as 5/C3.2. Verify correct reference.',
          status: 'Resolved',
          createdBy: 'AI Assistant',
          aiGenerated: true,
          timestamp: new Date(2024, 0, 16, 11, 0),
        },
        {
          id: 'issue-1-5',
          drawingId: 'drawing-1',
          pageNumber: 1,
          x: 0.15,
          y: 0.60,
          type: 'Missing Dimension/Callout',
          severity: 'Medium',
          description: 'Structural column spacing dimension not shown between Grids C-3 and C-4. Required for contractor layout.',
          status: 'Open',
          createdBy: 'Sarah Chen, PE',
          aiGenerated: false,
          timestamp: new Date(2024, 0, 17, 14, 20),
        },
        {
          id: 'issue-1-6',
          drawingId: 'drawing-1',
          pageNumber: 1,
          x: 0.65,
          y: 0.55,
          type: 'Visual Discrepancy',
          severity: 'Medium',
          description: 'Fire rating annotation shows 2-hour rating, but wall assembly detail indicates 3-hour. Verify correct rating.',
          status: 'In Review',
          createdBy: 'AI Assistant',
          aiGenerated: true,
          timestamp: new Date(2024, 0, 16, 15, 45),
        },
        {
          id: 'issue-1-7',
          drawingId: 'drawing-1',
          pageNumber: 1,
          x: 0.30,
          y: 0.15,
          type: 'Code Compliance Concern',
          severity: 'High',
          description: 'Egress path width appears to narrow to 36" at corridor transition. Minimum 44" required per IBC 1018.2.',
          status: 'Open',
          createdBy: 'AI Assistant',
          aiGenerated: true,
          timestamp: new Date(2024, 0, 16, 16, 10),
        },
        {
          id: 'issue-1-8',
          drawingId: 'drawing-1',
          pageNumber: 1,
          x: 0.80,
          y: 0.65,
          type: 'Grading/Elevation Issue',
          severity: 'Low',
          description: 'Drainage swale invert elevation not labeled. Add elevation callout for construction reference.',
          status: 'Resolved',
          createdBy: 'AI Assistant',
          aiGenerated: true,
          timestamp: new Date(2024, 0, 17, 9, 15),
        },
      ],
    },
    '2': { // River Walk Development
      'drawing-2': [
        {
          id: 'issue-2-1',
          drawingId: 'drawing-2',
          pageNumber: 1,
          x: 0.30,
          y: 0.35,
          type: 'Grading/Elevation Issue',
          severity: 'High',
          description: 'Flood control berm elevation conflicts with FEMA Base Flood Elevation. Verify 100-year flood elevation compliance.',
          status: 'Open',
          createdBy: 'AI Assistant',
          aiGenerated: true,
          timestamp: new Date(2024, 1, 4, 9, 20),
        },
        {
          id: 'issue-2-2',
          drawingId: 'drawing-2',
          pageNumber: 1,
          x: 0.60,
          y: 0.50,
          type: 'Missing Dimension/Callout',
          severity: 'Medium',
          description: 'Riverwalk boardwalk width dimension missing at Section A-A. Standard width is 8\', verify against specifications.',
          status: 'In Review',
          createdBy: 'AI Assistant',
          aiGenerated: true,
          timestamp: new Date(2024, 1, 4, 9, 25),
        },
        {
          id: 'issue-2-3',
          drawingId: 'drawing-2',
          pageNumber: 1,
          x: 0.45,
          y: 0.20,
          type: 'Code Compliance Concern',
          severity: 'Medium',
          description: 'Retaining wall height exceeds 4\' without structural engineer stamp. Required per IBC 1807.2.3.',
          status: 'Open',
          createdBy: 'AI Assistant',
          aiGenerated: true,
          timestamp: new Date(2024, 1, 4, 10, 0),
        },
        {
          id: 'issue-2-4',
          drawingId: 'drawing-2',
          pageNumber: 1,
          x: 0.20,
          y: 0.70,
          type: 'Specification Inconsistency',
          severity: 'Low',
          description: 'Riprap size specification shows Class A (12"-18"), but detail calls for Class B (6"-12"). Clarify correct specification.',
          status: 'Resolved',
          createdBy: 'AI Assistant',
          aiGenerated: true,
          timestamp: new Date(2024, 1, 5, 11, 30),
        },
        {
          id: 'issue-2-5',
          drawingId: 'drawing-2',
          pageNumber: 1,
          x: 0.70,
          y: 0.40,
          type: 'Visual Discrepancy',
          severity: 'Low',
          description: 'Pedestrian ramp slope annotation shows 1:12, but measured slope appears steeper. Verify actual slope.',
          status: 'Open',
          createdBy: 'Sarah Chen, PE',
          aiGenerated: false,
          timestamp: new Date(2024, 1, 6, 13, 45),
        },
        {
          id: 'issue-2-6',
          drawingId: 'drawing-2',
          pageNumber: 1,
          x: 0.50,
          y: 0.60,
          type: 'Grading/Elevation Issue',
          severity: 'Medium',
          description: 'Storm drain invert elevation at MH-12 not shown. Required for construction and as-built documentation.',
          status: 'In Review',
          createdBy: 'AI Assistant',
          aiGenerated: true,
          timestamp: new Date(2024, 1, 4, 14, 15),
        },
        {
          id: 'issue-2-7',
          drawingId: 'drawing-2',
          pageNumber: 1,
          x: 0.35,
          y: 0.80,
          type: 'Missing Dimension/Callout',
          severity: 'Low',
          description: 'Tree preservation area boundary not dimensioned. Add dimension line for field verification.',
          status: 'Resolved',
          createdBy: 'AI Assistant',
          aiGenerated: true,
          timestamp: new Date(2024, 1, 5, 16, 0),
        },
      ],
    },
    '3': { // Highland Residential Subdivision
      'drawing-3': [
        {
          id: 'issue-3-1',
          drawingId: 'drawing-3',
          pageNumber: 1,
          x: 0.25,
          y: 0.30,
          type: 'Grading/Elevation Issue',
          severity: 'High',
          description: 'Lot 12 finish floor elevation 342.5\' conflicts with street grade showing 341.8\'. Verify drainage flow direction.',
          status: 'Resolved',
          createdBy: 'AI Assistant',
          aiGenerated: true,
          timestamp: new Date(2023, 11, 11, 10, 0),
        },
        {
          id: 'issue-3-2',
          drawingId: 'drawing-3',
          pageNumber: 1,
          x: 0.55,
          y: 0.45,
          type: 'Missing Dimension/Callout',
          severity: 'Medium',
          description: 'Storm drain pipe diameter not labeled at catch basin CB-8. Standard is 15", verify against specifications.',
          status: 'Resolved',
          createdBy: 'AI Assistant',
          aiGenerated: true,
          timestamp: new Date(2023, 11, 11, 10, 15),
        },
        {
          id: 'issue-3-3',
          drawingId: 'drawing-3',
          pageNumber: 1,
          x: 0.70,
          y: 0.25,
          type: 'Code Compliance Concern',
          severity: 'High',
          description: 'Culvert size appears undersized for 25-year storm event. Verify hydraulic calculations per local drainage criteria.',
          status: 'Resolved',
          createdBy: 'AI Assistant',
          aiGenerated: true,
          timestamp: new Date(2023, 11, 11, 11, 30),
        },
        {
          id: 'issue-3-4',
          drawingId: 'drawing-3',
          pageNumber: 1,
          x: 0.40,
          y: 0.65,
          type: 'Specification Inconsistency',
          severity: 'Low',
          description: 'Pavement section detail calls for 6" base, but specifications indicate 8" minimum. Clarify correct thickness.',
          status: 'Resolved',
          createdBy: 'AI Assistant',
          aiGenerated: true,
          timestamp: new Date(2023, 11, 12, 9, 0),
        },
        {
          id: 'issue-3-5',
          drawingId: 'drawing-3',
          pageNumber: 1,
          x: 0.15,
          y: 0.55,
          type: 'Visual Discrepancy',
          severity: 'Medium',
          description: 'Property line setback dimension shows 25\', but measured distance appears closer to 20\'. Verify survey data.',
          status: 'Resolved',
          createdBy: 'Sarah Chen, PE',
          aiGenerated: false,
          timestamp: new Date(2023, 11, 12, 14, 20),
        },
        {
          id: 'issue-3-6',
          drawingId: 'drawing-3',
          pageNumber: 1,
          x: 0.60,
          y: 0.70,
          type: 'Grading/Elevation Issue',
          severity: 'Low',
          description: 'Retention pond bottom elevation not labeled. Add elevation callout for construction reference.',
          status: 'Resolved',
          createdBy: 'AI Assistant',
          aiGenerated: true,
          timestamp: new Date(2023, 11, 13, 10, 45),
        },
        {
          id: 'issue-3-7',
          drawingId: 'drawing-3',
          pageNumber: 1,
          x: 0.35,
          y: 0.15,
          type: 'Missing Dimension/Callout',
          severity: 'Medium',
          description: 'Sidewalk width dimension missing along Oak Street frontage. Standard is 5\', verify against ADA requirements.',
          status: 'Resolved',
          createdBy: 'AI Assistant',
          aiGenerated: true,
          timestamp: new Date(2023, 11, 13, 15, 30),
        },
        {
          id: 'issue-3-8',
          drawingId: 'drawing-3',
          pageNumber: 1,
          x: 0.80,
          y: 0.50,
          type: 'Code Compliance Concern',
          severity: 'High',
          description: 'Driveway slope exceeds 15% maximum grade. Verify compliance with local accessibility standards.',
          status: 'Resolved',
          createdBy: 'AI Assistant',
          aiGenerated: true,
          timestamp: new Date(2023, 11, 14, 9, 15),
        },
        {
          id: 'issue-3-9',
          drawingId: 'drawing-3',
          pageNumber: 1,
          x: 0.50,
          y: 0.35,
          type: 'Specification Inconsistency',
          severity: 'Low',
          description: 'Curb type specification shows Type B, but detail sheet indicates Type A. Verify correct curb type.',
          status: 'Resolved',
          createdBy: 'AI Assistant',
          aiGenerated: true,
          timestamp: new Date(2023, 11, 14, 11, 0),
        },
        {
          id: 'issue-3-10',
          drawingId: 'drawing-3',
          pageNumber: 1,
          x: 0.20,
          y: 0.75,
          type: 'Grading/Elevation Issue',
          severity: 'Medium',
          description: 'Grading plan shows cut/fill balance, but quantities table indicates net import. Verify earthwork calculations.',
          status: 'Resolved',
          createdBy: 'AI Assistant',
          aiGenerated: true,
          timestamp: new Date(2023, 11, 15, 13, 45),
        },
        {
          id: 'issue-3-11',
          drawingId: 'drawing-3',
          pageNumber: 1,
          x: 0.65,
          y: 0.20,
          type: 'Missing Dimension/Callout',
          severity: 'Low',
          description: 'Utility easement width not dimensioned. Add dimension line for legal documentation.',
          status: 'Resolved',
          createdBy: 'AI Assistant',
          aiGenerated: true,
          timestamp: new Date(2023, 11, 16, 10, 30),
        },
        {
          id: 'issue-3-12',
          drawingId: 'drawing-3',
          pageNumber: 1,
          x: 0.45,
          y: 0.60,
          type: 'Visual Discrepancy',
          severity: 'Medium',
          description: 'Storm drain pipe slope annotation shows 0.5%, but minimum required is 0.3%. Verify hydraulic calculations.',
          status: 'Resolved',
          createdBy: 'AI Assistant',
          aiGenerated: true,
          timestamp: new Date(2023, 11, 16, 14, 0),
        },
        {
          id: 'issue-3-13',
          drawingId: 'drawing-3',
          pageNumber: 1,
          x: 0.30,
          y: 0.40,
          type: 'Code Compliance Concern',
          severity: 'High',
          description: 'Fire hydrant spacing exceeds 500\' maximum distance. Add additional hydrant per NFPA 291 requirements.',
          status: 'Resolved',
          createdBy: 'AI Assistant',
          aiGenerated: true,
          timestamp: new Date(2023, 11, 17, 9, 20),
        },
        {
          id: 'issue-3-14',
          drawingId: 'drawing-3',
          pageNumber: 1,
          x: 0.75,
          y: 0.65,
          type: 'Grading/Elevation Issue',
          severity: 'Low',
          description: 'Top of curb elevation not labeled at street intersection. Add elevation callout for construction reference.',
          status: 'Resolved',
          createdBy: 'AI Assistant',
          aiGenerated: true,
          timestamp: new Date(2023, 11, 17, 11, 15),
        },
        {
          id: 'issue-3-15',
          drawingId: 'drawing-3',
          pageNumber: 1,
          x: 0.55,
          y: 0.80,
          type: 'Missing Dimension/Callout',
          severity: 'Medium',
          description: 'Retention pond outlet structure dimensions not shown. Required for construction and permit approval.',
          status: 'Resolved',
          createdBy: 'AI Assistant',
          aiGenerated: true,
          timestamp: new Date(2023, 11, 18, 10, 0),
        },
        {
          id: 'issue-3-16',
          drawingId: 'drawing-3',
          pageNumber: 1,
          x: 0.25,
          y: 0.50,
          type: 'Specification Inconsistency',
          severity: 'Low',
          description: 'Pavement marking specification calls for thermoplastic, but detail shows paint. Clarify correct material.',
          status: 'Resolved',
          createdBy: 'AI Assistant',
          aiGenerated: true,
          timestamp: new Date(2023, 11, 18, 14, 30),
        },
        {
          id: 'issue-3-17',
          drawingId: 'drawing-3',
          pageNumber: 1,
          x: 0.60,
          y: 0.30,
          type: 'Code Compliance Concern',
          severity: 'Medium',
          description: 'Sidewalk cross-slope appears to exceed 2% maximum. Verify compliance with ADA accessibility requirements.',
          status: 'Resolved',
          createdBy: 'AI Assistant',
          aiGenerated: true,
          timestamp: new Date(2023, 11, 19, 9, 45),
        },
        {
          id: 'issue-3-18',
          drawingId: 'drawing-3',
          pageNumber: 1,
          x: 0.40,
          y: 0.25,
          type: 'Grading/Elevation Issue',
          severity: 'High',
          description: 'Lot 8 finish floor elevation conflicts with adjacent lot drainage. Verify positive drainage away from structures.',
          status: 'Resolved',
          createdBy: 'AI Assistant',
          aiGenerated: true,
          timestamp: new Date(2023, 11, 19, 15, 0),
        },
        {
          id: 'issue-3-19',
          drawingId: 'drawing-3',
          pageNumber: 1,
          x: 0.70,
          y: 0.55,
          type: 'Missing Dimension/Callout',
          severity: 'Low',
          description: 'Utility vault cover size not specified. Standard is 30"x30", verify against utility company requirements.',
          status: 'Resolved',
          createdBy: 'AI Assistant',
          aiGenerated: true,
          timestamp: new Date(2023, 11, 20, 10, 20),
        },
        {
          id: 'issue-3-20',
          drawingId: 'drawing-3',
          pageNumber: 1,
          x: 0.15,
          y: 0.45,
          type: 'Visual Discrepancy',
          severity: 'Medium',
          description: 'Street centerline radius annotation shows 150\', but measured radius appears closer to 140\'. Verify survey.',
          status: 'Resolved',
          createdBy: 'AI Assistant',
          aiGenerated: true,
          timestamp: new Date(2023, 11, 20, 13, 30),
        },
        {
          id: 'issue-3-21',
          drawingId: 'drawing-3',
          pageNumber: 1,
          x: 0.50,
          y: 0.15,
          type: 'Code Compliance Concern',
          severity: 'High',
          description: 'Cul-de-sac radius appears less than 40\' minimum. Verify compliance with local subdivision regulations.',
          status: 'Resolved',
          createdBy: 'AI Assistant',
          aiGenerated: true,
          timestamp: new Date(2023, 11, 21, 9, 0),
        },
        {
          id: 'issue-3-22',
          drawingId: 'drawing-3',
          pageNumber: 1,
          x: 0.35,
          y: 0.70,
          type: 'Grading/Elevation Issue',
          severity: 'Low',
          description: 'Retention pond high water elevation not labeled. Add elevation callout for permit documentation.',
          status: 'Resolved',
          createdBy: 'AI Assistant',
          aiGenerated: true,
          timestamp: new Date(2023, 11, 21, 11, 45),
        },
        {
          id: 'issue-3-23',
          drawingId: 'drawing-3',
          pageNumber: 1,
          x: 0.65,
          y: 0.40,
          type: 'Specification Inconsistency',
          severity: 'Low',
          description: 'Storm drain pipe material specification shows HDPE, but detail indicates RCP. Clarify correct material type.',
          status: 'Resolved',
          createdBy: 'AI Assistant',
          aiGenerated: true,
          timestamp: new Date(2023, 11, 22, 14, 15),
        },
      ],
    },
  };

  return issues[projectId]?.[drawingId] || [];
}

